version: '3'

services:
  app:
    build: 
      context: instabug-rails
      dockerfile: Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: mysql2://root:password@db/instabug
      ELASTICSEARCH_URL: http://elasticsearch:9200
      RAILS_ENV: development
      SECRET_KEY_BASE: 6ea5ab12d212c45475af6ac7e1d72e018e401eff9357549196e23cc456df31336f138c994fa911bb77a3a65ad50c0919bdbc76b18b3b9bab42e59d1556fa489b
    restart: always


  db:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: instabug

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"


  writer-service:
    build:
      context: writer-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elasticsearch
      - redis
      - app
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      DATABASE_URL: root:password@tcp(db:3306)/instabug?parseTime=true
      REDIS_URL: redis:6379

  monitor:
    image: hibiken/asynqmon:latest
    environment:
      REDIS_URL: redis:6379
    ports:
      - "8081:8080" 
    depends_on:
      - writer-service

  worker1:
    build:
      context: worker
      dockerfile: Dockerfile
    # command: go run main.go
    restart: always
    depends_on:
      - db
      - redis
      - writer-service
      - app
    environment:
      REDIS_URL: redis:6379
      DATABASE_URL: root:password@tcp(db:3306)/instabug?parseTime=true


  nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - writer-service
      - worker1

volumes:
  db_data:
  redis_data:
  elasticsearch_data:
